language: php
sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - DB=sqlite
  - DB=mysql

matrix:
  fast_finish: true

before_script:
  - composer dump-autoload
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS picodb;" -uroot; fi

script:
  - phpunit --testsuite $DB